apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: lab1e1
spec:
  collectors:
    - logs:
        selector:
          - app=nginx
        namespace: '{{repl Namespace }}'
    - exec:
        name: check-config
        collectorName: check-config
        selector:
          - app=file-check-pod
        namespace: '{{repl Namespace}}'
        args:
        - stat
        - -c
        - "%a"
        - /etc/lab10/config.txt
  analyzers:
    - textAnalyze:
        checkName: Config Check
        fileName: check-config/{{repl Namespace}}/*/check-config-*.txt
        regex: '400'
        outcomes:
          - pass:
              message: Found properly-restricted file at /etc/lab10/config.txt
          - fail:
              message: Could not find a file at /etc/lab10/config.txt with 400 permissions -- please ensure this file exists with any content

